import { DoubleSide } from 'three';
import type { CreatureSpeciesDefinition } from '../SpeciesDefinition';
import { ammoniteAssets } from './ammoniteAssets';

export const ammoniteSpecies: CreatureSpeciesDefinition = {
  id: 'ammonite',
  name: { zhTW: '菊石', en: 'Ammonite' },
  scientificName: 'Ammonoidea',
  directionalAssets: ammoniteAssets,
  defaultScale: { width: 3.2, height: 3.2 },
  rendering: {
    mode: 'pitch_directional_8x3',
    billboard: 'cameraFacing',
    fallbackColor: 0xffa500,
    transparent: true,
    alphaTest: 0.05,
    side: DoubleSide,
    depthTest: true,
    depthWrite: false,
    fog: true,
    toneMapped: false,
  },
  orientation: {
    defaultHeadingDegrees: 90,
    directionalHysteresisDegrees: 5,
    maxBillboardPitchDegrees: 30,
    billboardPitchDeadZoneDegrees: 3,
    billboardPitchResponseSeconds: 0.18,
    billboardHorizontalEpsilon: 0.01,
    pitchLayerThresholdDegrees: 20,
    pitchLayerHysteresisDegrees: 5,
  },
  interaction: { interactionDistance: 6, minimumObservationDistance: 2.25 },
  movement: {
    enabled: true,
    locomotion: {
      enabled: true,
      mode: 'gentle_roam',
      horizontalRoamRadius: 3.5,
      cruiseSpeed: 0.26,
      acceleration: 0.16,
      deceleration: 0.22,
      slowdownRadius: 0.9,
      arrivalRadius: 0.18,
      maxTurnRateDegreesPerSecond: 24,
      minimumTargetDistance: 1.2,
      pauseMinSeconds: 1.2,
      pauseMaxSeconds: 2.8,
    },
    ambientMotion: {
      enabled: true,
      verticalAmplitude: 0.16,
      verticalPeriodSeconds: 5.5,
      driftXAmplitude: 0.14,
      driftXPeriodSeconds: 8,
      driftZAmplitude: 0.1,
      driftZPeriodSeconds: 6.7,
    },
  },
  animation: { enabled: false, framesPerDirection: 1 },
  behaviorProfile: 'gentle_drifter',
  spawnDefaults: { scaleMultiplier: 1 },
};
